version: "3.7"

x-logger: &logger
    logging:
      #driver: none
      driver: json-file
      options:
        max-size: "10M"
        max-file: "3"

x-networks: &networks
    networks:
      - service_net

x-deploy: &deploy-resources
      resources:
        limits:
          cpus: "0.2"
          memory: 200M

x-service-traefik: &service-traefik
  traefik:
    image: "wms-sklad-ng.dp.wb.ru:4567/devops/deployment/traefik:v2.4.2"
    command:
     --providers.file.directory=/configs
     --providers.file.watch=true
     --providers.docker=true
     --providers.docker.endpoint=unix:///var/run/docker.sock
     --providers.docker.swarmmode=true
     --providers.docker.exposedbydefault=false
     --providers.docker.network=service_net
     --providers.consul.endpoints=discovery_consul:8500
     --providers.consul.rootkey=wms-test
     --entrypoints.http.address=:80
     --api.insecure=true
     --api.dashboard=true
     --api=true
     --accesslog=true
     --accesslog.filters.statuscodes=200-510
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
      restart_policy:
        condition: on-failure
      <<: *deploy-resources
    <<: *logger
    <<: *networks
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/data/traefik:/configs:ro

x-service-consul: &service-consul
  consul:
    image: wms-sklad-ng.dp.wb.ru:4567/devops/deployment/consul:latest
    command:
      - "agent"
      - "-datacenter=wms-consul-production"
      - "-node=consul-01.fd.whs.wb.ru"
      - "-encrypt=NATIr1EC8CvBEHp4FYTAnFvRKCm4DB2uCpzXTgZBA14="
      - "-client=0.0.0.0"
      - "-advertise=10.156.2.80"
      - "-retry-join=wms-consul01.dp.wb.ru"
      - "-retry-join=wms-consul02.dl.wb.ru"
      - "-retry-join=wms-consul03.3d.wb.ru"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    <<: *logger
    <<: *networks
    ports:
      - "8300:8300"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8500:8500"
      - "8502:8502"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - /srv/data/consul:/consul/config

services:
    <<: *service-consul
    <<: *service-traefik

networks:
  service_net:
    name: service_net
    external: true